remote_theme: just-the-docs/just-the-docs
title: OData Lab
search_enabled: false
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2020-2020 <a href=\https://www.dpbird.com/\> DPBIRD </a>"