remote_theme: just-the-docs/just-the-docs
title: OData Lab

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

search_enabled: true

color_scheme: nil

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "OData Lab on GitHub":
    - "//github.com/dpbirdcom/ofbiz-odatalab/"

aux_links_new_tab: true

footer_content: "Copyright &copy; 2017-2022 <a href=\"http://www.dpbird.com/\">DPBIRD</a>."

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true